# defines the default code repository
code: https://github.com/hirenoble/helix-5.git#master
strains:
  default:
    content:
      owner: hirenoble
      repo: helix-5
      ref: e150fab47ca1df49ab0a4a0d289663b04775f577
